# Autogenerated wrapper script for SoapyLiteXM2SDR_jll for aarch64-linux-musl-cxx11
export libSoapyLiteXM2SDR

using soapysdr_jll
JLLWrappers.@generate_wrapper_header("SoapyLiteXM2SDR")
JLLWrappers.@declare_library_product(libSoapyLiteXM2SDR, "libSoapyLiteXM2SDR.so")
function __init__()
    JLLWrappers.@generate_init_header(soapysdr_jll)
    JLLWrappers.@init_library_product(
        libSoapyLiteXM2SDR,
        "lib/SoapySDR/modules0.8/libSoapyLiteXM2SDR.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
